language: cpp

linux-build: &linux-build
  dist: bionic
  script:
    - cd build
    - ./configure.sh
    - cd ../out/x64
    - make

matrix:
    include:
        - name: gcc linux
          compiler: gcc
          <<: *linux-build
        - name: clang linux
          compiler: clang
          <<: *linux-build
        - name: clang linux with static analysis
          compiler: clang
          env:
            - USE_STATIC_ANALYZER=1
            - CC=/usr/bin/clang-9
            - CXX=/usr/bin/clang++-9
            - CLANG_FORMAT=/usr/bin/clang-format-9
            - CLANG_TIDY=/usr/bin/clang-tidy-9
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get -qq -y install
              clang-9
              clang-tidy-9
              clang-tools-9
          <<: *linux-build
        - name: visual studio 2017 windows
          os: windows
          before_install:
            - choco install python
          script:
            - cd build
            - ./configure_2017.cmd
            - cd ../out/x64
            - cmake --build . --config RelWithDebInfo -- -verbosity:minimal
        - name: gcc virtualbox driver linux
          compiler: gcc
          dist: bionic
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get -qq -y install
              acpica-tools
              build-essential
              g++-multilib
              gcc-multilib
              libcap-dev
              libcurl4-openssl-dev
              libdevmapper-dev
              libidl-dev
              libelf-dev
              libopus-dev
              libpam0g-dev
              libqt5x11extras5-dev
              libsdl1.2-dev
              libsdl2-dev
              libssl-dev
              libvpx-dev
              libxml2-dev
              libxmu-dev
              linux-headers-$(uname -r)
              linux-libc-dev
              makeself
              nasm
              p7zip-full
              python-dev
              qt5-default
              qttools5-dev-tools
              xsltproc
          script:
            - cd third_party/virtualbox/include
            - ln -s ../../../src/FDP
            - cd ..
            - ./configure
              --disable-hardening
              --disable-docs
              --disable-java
            - source env.sh
            - kmk VBoxVMM
              VBOX_WITH_ADDITIONS=
              VBOX_WITH_TESTCASES=
              VBOX_WITH_TESTSUITE=
              VBOX_DO_STRIP=1
